version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: sudo apt-get install -y make git
      - run: CACHEDIR=.cache-linux sudo make deps-linux
      - run: sudo chown -R circleci ~/bin ~/.bazel
      - run: sudo make deps
      - run: PATH=~/bin:$PATH make ci
      - store_artifacts:
          path: tmp/build/
  build-and-test-upcoming-bazel-changes:
    docker:
      - image: circleci/buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: sudo apt-get install -y make git
      - run: CACHEDIR=.cache-linux sudo make deps-linux
      - run: sudo chown -R circleci ~/bin ~/.bazel
      - run: sudo make deps
      - run: PATH=~/bin:$PATH make test-upcoming-bazel-changes
      - store_artifacts:
          path: tmp/build/
  build-and-test-macos:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run: make deps
      - run: make ci
      - run: make ci-nextflags
      - store_artifacts:
          path: tmp/build/
workflows:
  version: 2
  commit:
    jobs:
      - build-and-test
      - build-and-test-macos
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-test
      - build-and-test-macos
